[project]
name = "DelPotro"
authors = []
description = "Demonstrates a basic NFT collection that conforms to the SIP-009 NFT standard called DelPotro"
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.DelPotro"

[contracts.DelPotro]
path = "contracts/DelPotro.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
